version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_desafio
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Desafio@Isadora
    ports:
      - "1433:1433"

  api:
    image: desafio-zetta-api
    build:
      context: .
      dockerfile: DesafioIIZetta.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ControleEmprestimo;User Id=sa;Password=Desafio@Isadora;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    depends_on:
      - db